#ELIMINACION DE PARTICIONES PRIMARIAS
fdisk -delete=full -name=Part2 -path=/tmp/d1.dk

#ELIMINACION DE PARTICIONES EXTENDIDAS
fdisk -delete=fast -name=Part1 -path=/tmp/d3.dk

#ELIMINACION DE PARTICIONES LOGICAS
fdisk -delete=full -name=Part3 -path=/tmp/d2.dk

#reporte disk despues de eliminar
rep -id=621a -Path=/home/parte1/particiones/d1.jpg -name=disk
rep -id=622a -Path=/home/parte1/particiones/d2.jpg -name=disk
rep -id=623a -Path=/home/parte1/particiones/d3.jpg -name=disk
